import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { Calendar, MapPin, Clock } from "lucide-react";
import { format } from "date-fns";
import { PrintPageButton } from "@/components/dashboard/PrintPageButton";

export default async function PrintTripPage(props: { params: Promise<{ id: string }> }) {
    const params = await props.params;
    const supabase = await createClient();

    const { data: trip } = await supabase.from("trips").select("*").eq("id", params.id).single();
    if (!trip) return notFound();

    const { data: activities } = await supabase
        .from("activities")
        .select("*")
        .eq("trip_id", params.id)
        .order("day_number", { ascending: true })
        .order("start_time", { ascending: true });

    // Group activities by day
    const activitiesByDay: Record<number, any[]> = {};
    activities?.forEach(act => {
        if (!activitiesByDay[act.day_number]) activitiesByDay[act.day_number] = [];
        activitiesByDay[act.day_number].push(act);
    });

    return (
        <div className="max-w-[210mm] mx-auto bg-white p-12 min-h-screen print:p-0 print:max-w-none">
            {/* Header */}
            <div className="border-b-2 border-deep-teak pb-6 mb-8">
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-heading font-bold text-deep-teak mb-2">{trip.title}</h1>
                        <div className="flex items-center gap-6 text-stone-gray">
                            <div className="flex items-center gap-1">
                                <MapPin className="w-5 h-5 text-terracotta" />
                                {trip.destination}
                            </div>
                            <div className="flex items-center gap-1">
                                <Calendar className="w-5 h-5 text-terracotta" />
                                {format(new Date(trip.start_date), "MMMM d")} - {format(new Date(trip.end_date), "MMMM d, yyyy")}
                            </div>
                        </div>
                    </div>
                    <div className="text-right hidden print:block">
                        <p className="text-sm text-stone-gray">Generated by ITINARA</p>
                    </div>
                </div>
            </div>

            {/* Itinerary */}
            <div className="space-y-8">
                {Object.keys(activitiesByDay).map((dayNum) => {
                    const dayActivities = activitiesByDay[parseInt(dayNum)];
                    const dayDate = new Date(trip.start_date);
                    dayDate.setDate(dayDate.getDate() + (parseInt(dayNum) - 1));

                    return (
                        <div key={dayNum} className="break-inside-avoid">
                            <h2 className="text-2xl font-bold text-deep-teak mb-4 flex items-center gap-3">
                                <span className="bg-deep-teak text-white w-8 h-8 rounded-full flex items-center justify-center text-sm">
                                    {dayNum}
                                </span>
                                {format(dayDate, "EEEE, MMMM d")}
                            </h2>

                            <div className="ml-4 border-l-2 border-stone-gray/10 pl-6 space-y-6">
                                {dayActivities.map((act) => (
                                    <div key={act.id} className="grid grid-cols-[80px_1fr] gap-4">
                                        <div className="text-sm font-bold text-stone-gray flex items-center gap-1 pt-1">
                                            <Clock className="w-3 h-3 text-terracotta" />
                                            {act.start_time ? act.start_time.slice(0, 5) : "--:--"}
                                        </div>
                                        <div>
                                            <h3 className="font-bold text-lg text-deep-teak mb-1">{act.title}</h3>
                                            {act.location && (
                                                <p className="text-sm text-stone-gray italic mb-2">{act.location}</p>
                                            )}
                                            {act.notes && (
                                                <p className="text-sm text-stone-gray/80 leading-relaxed">{act.notes}</p>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    );
                })}
            </div>

            <div className="mt-12 pt-6 border-t border-stone-gray/10 text-center text-sm text-stone-gray print:hidden">
                <PrintPageButton />
            </div>
        </div>
    );
}
