"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

/**
 * Generate or retrieve a referral link for a template
 */
export async function generateReferralLink(templateId: string) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return { error: "Unauthorized" };
    }

    // Verify the user owns this template
    const { data: template } = await supabase
        .from("trip_templates")
        .select("id, guide_id")
        .eq("id", templateId)
        .single();

    if (!template || template.guide_id !== user.id) {
        return { error: "Template not found or unauthorized" };
    }

    // Check if referral link already exists
    const { data: existingLink } = await supabase
        .from("template_referral_links")
        .select("*")
        .eq("template_id", templateId)
        .single();

    if (existingLink) {
        return {
            success: true,
            refCode: existingLink.ref_code,
            url: `${process.env.NEXT_PUBLIC_APP_URL}/t/${existingLink.ref_code}`
        };
    }

    // Create new referral link (ref_code will be auto-generated by trigger)
    const { data: newLink, error } = await supabase
        .from("template_referral_links")
        .insert({
            template_id: templateId,
            guide_id: user.id,
        })
        .select()
        .single();

    if (error) {
        console.error("Error creating referral link:", error);
        return { error: "Failed to create referral link" };
    }

    return {
        success: true,
        refCode: newLink.ref_code,
        url: `${process.env.NEXT_PUBLIC_APP_URL}/t/${newLink.ref_code}`
    };
}

/**
 * Get analytics for a template's referral link
 */
export async function getReferralAnalytics(templateId: string) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return { error: "Unauthorized" };
    }

    // Get analytics from the view
    const { data: analytics, error } = await supabase
        .from("template_referral_analytics")
        .select("*")
        .eq("template_id", templateId)
        .eq("guide_id", user.id)
        .single();

    if (error) {
        // If no referral link exists yet, return empty analytics
        if (error.code === "PGRST116") {
            return {
                success: true,
                analytics: {
                    total_views: 0,
                    total_clicks: 0,
                    total_purchases: 0,
                    unique_visitors: 0,
                    conversion_rate: 0,
                    ref_code: null,
                }
            };
        }
        console.error("Error fetching referral analytics:", error);
        return { error: "Failed to fetch analytics" };
    }

    return {
        success: true,
        analytics: {
            total_views: analytics.total_views || 0,
            total_clicks: analytics.total_clicks || 0,
            total_purchases: analytics.total_purchases || 0,
            unique_visitors: analytics.unique_visitors || 0,
            conversion_rate: analytics.conversion_rate || 0,
            ref_code: analytics.ref_code,
            created_at: analytics.created_at,
        }
    };
}

/**
 * Get recent referral events for a template
 */
export async function getRecentReferralEvents(templateId: string, limit = 20) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return { error: "Unauthorized" };
    }

    // First get the ref_code for this template
    const { data: refLink } = await supabase
        .from("template_referral_links")
        .select("ref_code")
        .eq("template_id", templateId)
        .eq("guide_id", user.id)
        .single();

    if (!refLink) {
        return { success: true, events: [] };
    }

    // Get recent events
    const { data: events, error } = await supabase
        .from("template_referral_events")
        .select("*")
        .eq("ref_code", refLink.ref_code)
        .order("created_at", { ascending: false })
        .limit(limit);

    if (error) {
        console.error("Error fetching referral events:", error);
        return { error: "Failed to fetch events" };
    }

    return { success: true, events: events || [] };
}

/**
 * Delete a referral link (disables tracking)
 */
export async function deleteReferralLink(templateId: string) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return { error: "Unauthorized" };
    }

    const { error } = await supabase
        .from("template_referral_links")
        .delete()
        .eq("template_id", templateId)
        .eq("guide_id", user.id);

    if (error) {
        console.error("Error deleting referral link:", error);
        return { error: "Failed to delete referral link" };
    }

    revalidatePath(`/dashboard/templates/${templateId}`);
    return { success: true };
}
